package Regression.PDP;

import Automation.TestBase;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

/**
 * Created with IntelliJ IDEA.
 * User: KHALLBEC
 * Date: 3/17/13
 * Time: 6:22 PM
 * To change this template use File | Settings | File Templates.
 */
public class PDPAccessories48553 extends TestBase {


    String testNumber = "48553";
    String typeOfTest = "Regression";
    String typeOfCust = "NI";
    String typeOfPayment = "Credit";
    String searchResultAccessoriesPage = "Accessories";
    String searchAllBrand1 = "Zaditor";
    String searchAllBrand2 = "opti-free";
    String searchAllBrand3 = "solution";
    String searchAllBrand4 = "Accessories";
    String searchAllBrand5 = "puremoist";
    String searchAllBrand6 = "replenish";
    String searchAllBrand7 = "pure moist";
    String searchAllBrand8 = "Antihistamine";
    String searchAllBrand9 = "eye drops";
    String searchAllBrand10 = "Alcon";
    String search11 = "Opti-Free PureMoist Drops";
    String search12 = "Opti-Free PureMoist MPS";
    String search13 = "Opti-Free PureMoist MPS";
    String search14 = "Opti-Free Replenish MPS 2pk";
    String search15 = "Zaditor Eye Drops 2pk";
    String search16 = "2 ounce solution";
    String search17 = "2oz";
    String search18 = "2oz solution";
    String search19 = "accessories";
    String search20 = "ActiFresh 400";
    String search21 = "additions";
    String search22 = "aeosept";
    //String Alcon	";
    String search23 = "Alcon Opti-Free";
    String search24 = "ao sept";
    String search25 = "Ao spet";
    String search26 = "aosept";
    String search27 = "aosept clear care";
    String search28 = "aosept solution";
    String search29 = "aqua sof";
    String search30 = "aqua soft";
    String search31 = "Aqua Soft Multi-purpose solution";
    String search32 = "aqua soft rewetting drops";
    String search33 = "Aqua Soft solution";
    String search34 = "aquaflex";
    String search35 = "aquafy";
    String search36 = "aquafy solution";
    String search37 = "AquaSoft";
    String search38 = "AquaSoft cleaning solution";
    String search39 = "aquasoft drops";
    String search40 = "AquaSoft No-Rub Solution";
    String search41 = "Aquasoft rewetting drops";
    String search42 = "AquaSoft Re-Wetting Drops";
    String search43 = "aquasoft solution";
    String search44 = "AquaSoft Solution Bonus";
    String search45 = "AquaSoft Total Package";
    String search46 = "aquasofta";
    String search47 = "aquify";
    String search48 = "Aquify 12 oz No Rub Solution";
    String search49 = "Aquify no rub solution";
    String search50 = "Aquify norub solution";
    String search51 = "Aquify no-rub solution";
    String search52 = "aquify solution";
    String search53 = "Aquify Solution Bonus 4-pack";
    String search54 = "Aquify Total Package";
    String search55 = "bio true";
    String search56 = "biotrue";
    String search57 = "blink eye drops";
    String search58 = "blink n clean drops";
    String search59 = "boston contact lenses solution";
    String search60 = "care ciba clear vision";
    String search61 = "case";
    String search62 = "case contact lens mirror";
    String search63 = "case contact lens travel";
    String search64 = "case contact lenses mirror";
    String search65 = "case contact lenses travel";
    String search66 = "cases";
    String search67 = "ciba clear care";
    String search68 = "ciba saline";
    String search69 = "ciba saline solutions";
    String search70 = "ciba solution";
    String search71 = "CibaVision Clear Care";
    String search72 = "clean";
    String search73 = "clean and clear";
    String search74 = "clean care";
    String search75 = "cleaner";
    String search76 = "cleaner contact lens";
    String search77 = "cleaner contact lense";
    String search78 = "cleaner contact lenses";
    String search79 = "cleaners";
    String search80 = "cleaning";
    String search81 = "cleaning products";
    String search82 = "Cleaning Solution";
    String search83 = "cleaning solutions";
    String search84 = "cleanser";
    String search85 = "cleansers";
    String search86 = "clear care";
    String search87 = "clear care ciba vision";
    String search88 = "Clear Care Contact Solution";
    String search89 = "clear care solution";
    String search90 = "clear crae";
    String search91 = "Clear Eyes";
    String search92 = "String clear pluz";
    String search93 = "clear view";
    String search94 = "clear vue";
    String search95 = "clearcare";
    String search96 = "clensatron";
    String search97 = "complete";
    String search98 = "complete moisture";
    String search99 = "complete moisture plus";
    String search100 = "Complete Multipurpose solution";
    String search101 = "complete solution";
    String search102 = "contact case";
    String search103 = "Contact Cases";
    String search104 = "contact cleaner";
    String search105 = "contact drop eye lens";
    String search106 = "contact drop eye lenses";
    String search107 = "contact drop eyes lens";
    String search108 = "contact dry eyes";
    String search109 = "contact eye free";
    String search110 = "contact holder";
    String search111 = "contact lens and dry eyes";
    String search112 = "contact lens care";
    String search113 = "contact lens case";
    String search114 = "contact lens cases";
    String search115 = "contact lens cleaner";
    String search116 = "contact lens solution uk";
    String search117 = "contact lens solutions";
    String search118 = "contact lens storage case";
    String search119 = "contact lense care";
    String search120 = "contact lense case";
    String  search121 = "contact lense cleaner";
    String  search122 = "contact lense express";
    String  search123 = "contact lense solution";
    String  search124 = "contact lenses and dry eye";
    String  search125 = "contact lenses care";
    String  search126 = "contact lenses case";
    String  search127 = "contact lenses express";
    String   search128 = "contact lenses solution";
    String  search129 = "contact lenses storage case";
    String  search130 = "contact solution";
    String  search131 = "contact solutions";
    String search132 = "disinfect";
    String  search133 = "disinfectant";
    String  search134 = "disinfecting solution";
    String  search135 = "drops";
    String  search136 = "dry";
    String  search137 = "dry eye";
    String  search138 = "dry eyes";
    String  search139 = "equate";
    String  search140 = "equate lubricating & rewetting drops";
    String  search141 = "equate lubricating & rewetting drops twin pack";
    String  search142 = "equate lubricating and rewetting drops";
    String  search143 = "equate lubricating and rewetting drops twin pack";
    String  search144 = "equate lubricating drops";
    String   search145 = "equate multi-purpose solution";
    String  search146 = "equate multi-purpose solution 2oz";
    String  search147 = "equate rewetting drops";
    String   search148 = "equate rewetting drops twin pack";
    String   search149 = "equate solution";
    String  search150 = "eye contact lens care";
    String  search151 = "eye drop";
    String  search152 = "eye drops";
    String   search153 = "eye lubricant";
    String   search154 = "eye solution";
    String  search155 = "eye solutions";
    String   search156 = "eyedrops";
    String  search157 = "eyes care contact";
    String  search158 = "eyes contact lens";
    String search159 = "Focus Aqua";
    String  search160 = "Focus Drops";
    String  search161 = "focus lubricating drops";
    String  search162 = "Focus Rewetting drops";
    String  search163 = "Focus wetting drops";
    String  search164 = "holder";
    String  search165 = "hydrating";
    String  search166 = "lens case";
    String   search167 = "Lens Cases";
    String  search168 = "lens cleaner";
    String  search169 = "lens cleaners";
    String  search170 = "lens drops";
    String  search171 = "lens plus";
    String  search172 = "Lens Solution";
    String   search173 = "lens solutions";
    String   search174 = "lense case";
    String   search175 = "lense cases";
    String  search176 = "lense cleaner";
    String search177 = "limited quantities";
    String search178 = "lubricant eye drops";
    String   search179 = "miraflow";
    String   search180 = "mirror";
    String  search181 = "moisture";
    String  search182 = "moisture drops";
    String  search183 = "moisture loc";
    String  search184 = "moisture lock";
    String  search185 = "moistureloc";
    String  search186 = "moisturelock";
    String  search187 = "multiplus";
    String  search188 = "multipurpose";
    String   search189 = "multi-purpose";
    String  search190 = "multipurpose solution";
    String  search191 = "multi-purpose solution";
    String  search192 = "no rub";
    String   search193 = "no rub solution";
    String   search194 = "norub";
    String  search195 = "no-rub";
    String  search196 = "ocuclear";
    String  search197 = "Ocupure	";
    String  search198 = "ocupure 55";
    String  search199 = "opti";
    String  search200 = "opti clean";
    String  search201 = "opti free";
    String  search202 = "Opti Free Express";
    String  search203 = "opti free replenish";
    String  search204 = "opti free solution";
    String  search205 = "opti frsh";
    String  search206 = "opti one";
    String  search207 = "optifree";
    String  search208 = "Opti-Free";
    String  search209 = "optifree express";
    String   search210 = "opti-free express";
    String  search211 = "optifree replenish";
    String  search212 = "Opti-free RepleniSH";
    String  search213 = "Opti-free Solution";
    String  search214 = "optifres";
    String  search215 = "optione";
    String   search216 = "opti-one";
    String   search217 = "Optiva";
    String   search218 = "protein remover";
    String   search219 = "pure eyes";
    String   search220 = "pureeyes";
    String   search221 = "quickcare";
    String  search222 = "re wetting drops";
    String  search223 = "refresh";
    String  search224 = "refresh contact drops";
    String  search225 = "refresh plus";
    String  search226 = "refresh tears";
    String   search227 = "renew";
    String   search228 = "renu";
    String  search229 = "ReNu MultiPlus";
    String  search230 = "renu no rub";
    String  search231 = "renu solution";
    String  search232 = "renu with moistureloc";
    String  search233 = "renue";
    String  search234 = "replenish";
    String  search235 = "Replens";
    String  search236 = "rewet";
    String  search237 = "rewetting";
    String  search238 = "re-wetting";
    String   search239 = "rewetting drops";
    String   search240 = "rewetting solution";
    String  search241 = "saliene";
    String  search242 = "saline";
    String  search243 = "saline solution";
    String  search244 = "sauflon";
    String  search245 = "sauflon uv";
    String  search246 = "sensitive eyes";
    String  search247 = "small aquasoft";
    String   search248 = "small bottle";
    String   search249 = "small bottle of solution";
    String   search250 = "small no-rub solution";
    String   search251 = "small solution";
    String   search252 = "small solution bottle";
    String   search253 = "SoftWear Saline 12 oz";
    String   search254 = "solo";
    String   search255 = "solo care";
    String    search256 = "solocare";
    String  search257 = "SOLO-Care 12 oz";
    String  search258 = "Solo-Care 12 oz (Special)";
    String  search259 = "solus";
    String   search260 = "Solution";
    String   search261 = "solution,aquasoft cleaning solution";
    String   search262 = "solution,clear care";
    String   search263 = "solution,clear care solution";
    String  search264 = "solution,complete";
    String  search265 = "solution,opti free";
    String  search266 = "solution,opti free replenish";
    String search267 = "solution,optifree";
    String   search268 = "solution,opti-free";
    String  search269 = "solution,optifree express";
    String  search270 = "solution,optifree replenish";
    String  search271 = "solution,opti-free replenish";
    String  search272 = "solution,renu";
    String  search273 = "solution,replenish";
    String  search274 = "solution,replens";
    String  search275 = "solution,saline";
    String   search276 = "solution,sauflon";
    String   search277 = "solution,solus";
    String  search278 = "solution,solution";
    String  search279 = "solution,solutions";
    String  search280 = "solutionclear care";
    String  search281 = "solutionopti free";
    String  search282 = "solutionoptifree";
    String  search283 = "solutionopti-free";
    String  search284 = "solutionrenu";
    String  search285 = "solutionreplenish";
    String  search286 = "solutionreplens";
    String search287 = "solutions";
    String search288 = "solutionsaline";
    String  search289 = "solutionsauflon";
    String  search290 = "solutionsolutions";
    String search291 = "systane";
    String search292 = "travel";
    String  search293 = "travel bag";
    String  search294 = "travel bottle";
    String search295 = "travel case";
    String search296 = "travel kit";
    String search297 = "visine";
    String search298 = "wetting drops";
    String search299 = "wetting solution";

    String seperator = "/";
    String printTestName = typeOfTest + " | " + testNumber + " | " + typeOfCust + " | " + searchAllBrand4 + " | " + typeOfPayment;
    String screenshotTestName =  testNumber + "_" + typeOfTest + "_" + typeOfCust + "_" + searchAllBrand4 + "_" + typeOfPayment + "_" + seperator;


    @Test (singleThreaded = true)
    @Parameters(value = "device")
    public void test(String device) {
        openWebPage(device);
        takeScreenshot(screenshotTestName, "Interstitial");
        clickNoThanksButton(device);
        printTestNumber(printTestName);
        searchAllBrand(device,searchAllBrand1);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand1);
        searchAllBrand(device,searchAllBrand2);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand2);
        searchAllBrand(device,searchAllBrand3);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand3);
        //
        searchAllBrand(device,searchAllBrand4);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand4);
        //
        searchAllBrand(device,searchAllBrand5);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand5);
        searchAllBrand(device,searchAllBrand6);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand6);
        searchAllBrand(device,searchAllBrand7);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand7);
        searchAllBrand(device,searchAllBrand8);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand8);
        //
        searchAllBrand(device,searchAllBrand9);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand9);
        //
        searchAllBrand(device,searchAllBrand10);
        verifyProduct(device,searchResultAccessoriesPage,searchAllBrand10);
        searchAllBrand(device,search11);
        verifyProduct(device,searchResultAccessoriesPage,search11);
        searchAllBrand(device,search12);
        verifyProduct(device,searchResultAccessoriesPage,search12);
        searchAllBrand(device,search13);
        verifyProduct(device,searchResultAccessoriesPage,search13);
        searchAllBrand(device,search14);
        verifyProduct(device,searchResultAccessoriesPage,search14);
        searchAllBrand(device,search15);
        verifyProduct(device,searchResultAccessoriesPage,search15);
        searchAllBrand(device,search16);
        verifyProduct(device,searchResultAccessoriesPage,search16);
        searchAllBrand(device,search17);
        verifyProduct(device,searchResultAccessoriesPage,search17);
        searchAllBrand(device,search18);
        verifyProduct(device,searchResultAccessoriesPage,search18);
        searchAllBrand(device,search19);
        verifyProduct(device,searchResultAccessoriesPage,search19);
        searchAllBrand(device,search20);
        verifyProduct(device,searchResultAccessoriesPage,search20);
        searchAllBrand(device,search21);
        verifyProduct(device,searchResultAccessoriesPage,search21);
        searchAllBrand(device,search22);
        verifyProduct(device,searchResultAccessoriesPage,search22);
        searchAllBrand(device,search23);
        verifyProduct(device,searchResultAccessoriesPage,search23);
        searchAllBrand(device,search24);
        verifyProduct(device,searchResultAccessoriesPage,search24);
        searchAllBrand(device,search25);
        verifyProduct(device,searchResultAccessoriesPage,search25);
        searchAllBrand(device,search26);
        verifyProduct(device,searchResultAccessoriesPage,search26);
        searchAllBrand(device,search27);
        verifyProduct(device,searchResultAccessoriesPage,search27);
        searchAllBrand(device,search28);
        verifyProduct(device,searchResultAccessoriesPage,search28);
        searchAllBrand(device,search29);
        verifyProduct(device,searchResultAccessoriesPage,search29);
        searchAllBrand(device,search30);
        verifyProduct(device,searchResultAccessoriesPage,search30);
        searchAllBrand(device,search31);
        verifyProduct(device,searchResultAccessoriesPage,search31);
        searchAllBrand(device,search32);
        verifyProduct(device,searchResultAccessoriesPage,search32);
        searchAllBrand(device,search33);
        verifyProduct(device,searchResultAccessoriesPage,search33);
        searchAllBrand(device,search34);
        verifyProduct(device,searchResultAccessoriesPage,search34);
        searchAllBrand(device,search35);
        verifyProduct(device,searchResultAccessoriesPage,search35);
        searchAllBrand(device,search36);
        verifyProduct(device,searchResultAccessoriesPage,search36);
        searchAllBrand(device,search37);
        verifyProduct(device,searchResultAccessoriesPage,search37);
        searchAllBrand(device,search38);
        verifyProduct(device,searchResultAccessoriesPage,search38);
        searchAllBrand(device,search39);
        verifyProduct(device,searchResultAccessoriesPage,search39);
        searchAllBrand(device,search40);
        verifyProduct(device,searchResultAccessoriesPage,search40);
        searchAllBrand(device,search41);
        verifyProduct(device,searchResultAccessoriesPage,search41);
        searchAllBrand(device,search42);
        verifyProduct(device,searchResultAccessoriesPage,search42);
        searchAllBrand(device,search43);
        verifyProduct(device,searchResultAccessoriesPage,search43);
        searchAllBrand(device,search44);
        verifyProduct(device,searchResultAccessoriesPage,search44);
        searchAllBrand(device,search45);
        verifyProduct(device,searchResultAccessoriesPage,search45);
        searchAllBrand(device,search46);
        verifyProduct(device,searchResultAccessoriesPage,search46);
        searchAllBrand(device,search47);
        verifyProduct(device,searchResultAccessoriesPage,search47);
        searchAllBrand(device,search48);
        verifyProduct(device,searchResultAccessoriesPage,search48);
        searchAllBrand(device,search49);
        verifyProduct(device,searchResultAccessoriesPage,search49);
        searchAllBrand(device,search50);
        verifyProduct(device,searchResultAccessoriesPage,search50);
        searchAllBrand(device,search51);
        verifyProduct(device,searchResultAccessoriesPage,search51);
        searchAllBrand(device,search52);
        verifyProduct(device,searchResultAccessoriesPage,search52);
        searchAllBrand(device,search53);
        verifyProduct(device,searchResultAccessoriesPage,search53);
        searchAllBrand(device,search54);
        verifyProduct(device,searchResultAccessoriesPage,search54);
        searchAllBrand(device,search55);
        verifyProduct(device,searchResultAccessoriesPage,search55);
        searchAllBrand(device,search56);
        verifyProduct(device,searchResultAccessoriesPage,search56);
        searchAllBrand(device,search57);
        verifyProduct(device,searchResultAccessoriesPage,search57);
        searchAllBrand(device,search58);
        verifyProduct(device,searchResultAccessoriesPage,search58);
        searchAllBrand(device,search59);
        verifyProduct(device,searchResultAccessoriesPage,search59);
        searchAllBrand(device,search60);
        verifyProduct(device,searchResultAccessoriesPage,search60);
        searchAllBrand(device,search61);
        verifyProduct(device,searchResultAccessoriesPage,search61);
        searchAllBrand(device,search62);
        verifyProduct(device,searchResultAccessoriesPage,search62);
        searchAllBrand(device,search63);
        verifyProduct(device,searchResultAccessoriesPage,search63);
        searchAllBrand(device,search64);
        verifyProduct(device,searchResultAccessoriesPage,search64);
        searchAllBrand(device,search65);
        verifyProduct(device,searchResultAccessoriesPage,search65);
        searchAllBrand(device,search66);
        verifyProduct(device,searchResultAccessoriesPage,search66);
        searchAllBrand(device,search67);
        verifyProduct(device,searchResultAccessoriesPage,search67);
        searchAllBrand(device,search68);
        verifyProduct(device,searchResultAccessoriesPage,search68);
        searchAllBrand(device,search69);
        verifyProduct(device,searchResultAccessoriesPage,search69);
        searchAllBrand(device,search70);
        verifyProduct(device,searchResultAccessoriesPage,search70);
        searchAllBrand(device,search71);
        verifyProduct(device,searchResultAccessoriesPage,search71);
        searchAllBrand(device,search72);
        verifyProduct(device,searchResultAccessoriesPage,search72);
        searchAllBrand(device,search73);
        verifyProduct(device,searchResultAccessoriesPage,search73);
        searchAllBrand(device,search74);
        verifyProduct(device,searchResultAccessoriesPage,search74);
        searchAllBrand(device,search75);
        verifyProduct(device,searchResultAccessoriesPage,search75);
        searchAllBrand(device,search76);
        verifyProduct(device,searchResultAccessoriesPage,search76);
        searchAllBrand(device,search77);
        verifyProduct(device,searchResultAccessoriesPage,search77);
        searchAllBrand(device,search78);
        verifyProduct(device,searchResultAccessoriesPage,search78);
        searchAllBrand(device,search79);
        verifyProduct(device,searchResultAccessoriesPage,search79);
        searchAllBrand(device,search80);
        verifyProduct(device,searchResultAccessoriesPage,search80);
        searchAllBrand(device,search81);
        verifyProduct(device,searchResultAccessoriesPage,search81);
        searchAllBrand(device,search82);
        verifyProduct(device,searchResultAccessoriesPage,search82);
        searchAllBrand(device,search83);
        verifyProduct(device,searchResultAccessoriesPage,search83);
        searchAllBrand(device,search84);
        verifyProduct(device,searchResultAccessoriesPage,search84);
        searchAllBrand(device,search85);
        verifyProduct(device,searchResultAccessoriesPage,search85);
        searchAllBrand(device,search86);
        verifyProduct(device,searchResultAccessoriesPage,search86);
        searchAllBrand(device,search87);
        verifyProduct(device,searchResultAccessoriesPage,search87);
        searchAllBrand(device,search88);
        verifyProduct(device,searchResultAccessoriesPage,search88);
        searchAllBrand(device,search89);
        verifyProduct(device,searchResultAccessoriesPage,search89);
        searchAllBrand(device,search90);
        verifyProduct(device,searchResultAccessoriesPage,search90);
        searchAllBrand(device,search91);
        verifyProduct(device,searchResultAccessoriesPage,search91);
        searchAllBrand(device,search92);
        verifyProduct(device,searchResultAccessoriesPage,search92);
        searchAllBrand(device,search93);
        verifyProduct(device,searchResultAccessoriesPage,search93);
        searchAllBrand(device,search94);
        verifyProduct(device,searchResultAccessoriesPage,search94);
        searchAllBrand(device,search95);
        verifyProduct(device,searchResultAccessoriesPage,search95);
        searchAllBrand(device,search96);
        verifyProduct(device,searchResultAccessoriesPage,search96);
        searchAllBrand(device,search97);
        verifyProduct(device,searchResultAccessoriesPage,search97);
        searchAllBrand(device,search98);
        verifyProduct(device,searchResultAccessoriesPage,search98);
        searchAllBrand(device,search99);
        verifyProduct(device,searchResultAccessoriesPage,search99);
        searchAllBrand(device,search100);
        verifyProduct(device,searchResultAccessoriesPage,search100);

        searchAllBrand(device,search101);
        verifyProduct(device,searchResultAccessoriesPage,search101);
        searchAllBrand(device,search102);
        verifyProduct(device,searchResultAccessoriesPage,search102);
        searchAllBrand(device,search103);
        verifyProduct(device,searchResultAccessoriesPage,search103);
        searchAllBrand(device,search104);
        verifyProduct(device,searchResultAccessoriesPage,search104);
        searchAllBrand(device,search105);
        verifyProduct(device,searchResultAccessoriesPage,search105);
        searchAllBrand(device,search106);
        verifyProduct(device,searchResultAccessoriesPage,search106);
        searchAllBrand(device,search107);
        verifyProduct(device,searchResultAccessoriesPage,search107);
        searchAllBrand(device,search108);
        verifyProduct(device,searchResultAccessoriesPage,search108);
        searchAllBrand(device,search109);
        verifyProduct(device,searchResultAccessoriesPage,search109);
        searchAllBrand(device,search110);
        verifyProduct(device,searchResultAccessoriesPage,search110);
        searchAllBrand(device,search111);
        verifyProduct(device,searchResultAccessoriesPage,search111);
        searchAllBrand(device,search112);
        verifyProduct(device,searchResultAccessoriesPage,search112);
        searchAllBrand(device,search113);
        verifyProduct(device,searchResultAccessoriesPage,search113);
        searchAllBrand(device,search114);
        verifyProduct(device,searchResultAccessoriesPage,search114);
        searchAllBrand(device,search115);
        verifyProduct(device,searchResultAccessoriesPage,search115);
        searchAllBrand(device,search116);
        verifyProduct(device,searchResultAccessoriesPage,search116);
        searchAllBrand(device,search117);
        verifyProduct(device,searchResultAccessoriesPage,search117);
        searchAllBrand(device,search118);
        verifyProduct(device,searchResultAccessoriesPage,search118);
        searchAllBrand(device,search119);
        verifyProduct(device,searchResultAccessoriesPage,search119);
        searchAllBrand(device,search120);
        verifyProduct(device,searchResultAccessoriesPage,search120);
        searchAllBrand(device,search121);
        verifyProduct(device,searchResultAccessoriesPage,search121);
        searchAllBrand(device,search122);
        verifyProduct(device,searchResultAccessoriesPage,search122);
        searchAllBrand(device,search123);
        verifyProduct(device,searchResultAccessoriesPage,search123);
        searchAllBrand(device,search124);
        verifyProduct(device,searchResultAccessoriesPage,search124);
        searchAllBrand(device,search125);
        verifyProduct(device,searchResultAccessoriesPage,search125);
        searchAllBrand(device,search126);
        verifyProduct(device,searchResultAccessoriesPage,search126);
        searchAllBrand(device,search127);
        verifyProduct(device,searchResultAccessoriesPage,search127);
        searchAllBrand(device,search128);
        verifyProduct(device,searchResultAccessoriesPage,search128);
        searchAllBrand(device,search129);
        verifyProduct(device,searchResultAccessoriesPage,search129);
        searchAllBrand(device,search130);
        verifyProduct(device,searchResultAccessoriesPage,search130);
        searchAllBrand(device,search131);
        verifyProduct(device,searchResultAccessoriesPage,search131);
        searchAllBrand(device,search132);
        verifyProduct(device,searchResultAccessoriesPage,search132);
        searchAllBrand(device,search133);
        verifyProduct(device,searchResultAccessoriesPage,search133);
        searchAllBrand(device,search134);
        verifyProduct(device,searchResultAccessoriesPage,search134);
        searchAllBrand(device,search135);
        verifyProduct(device,searchResultAccessoriesPage,search135);
        searchAllBrand(device,search136);
        verifyProduct(device,searchResultAccessoriesPage,search136);
        searchAllBrand(device,search137);
        verifyProduct(device,searchResultAccessoriesPage,search137);
        searchAllBrand(device,search138);
        verifyProduct(device,searchResultAccessoriesPage,search138);
        searchAllBrand(device,search139);
        verifyProduct(device,searchResultAccessoriesPage,search139);
        searchAllBrand(device,search140);
        verifyProduct(device,searchResultAccessoriesPage,search140);
        searchAllBrand(device,search141);
        verifyProduct(device,searchResultAccessoriesPage,search141);
        searchAllBrand(device,search142);
        verifyProduct(device,searchResultAccessoriesPage,search142);
        searchAllBrand(device,search143);
        verifyProduct(device,searchResultAccessoriesPage,search143);
        searchAllBrand(device,search144);
        verifyProduct(device,searchResultAccessoriesPage,search144);
        searchAllBrand(device,search145);
        verifyProduct(device,searchResultAccessoriesPage,search145);
        searchAllBrand(device,search146);
        verifyProduct(device,searchResultAccessoriesPage,search146);
        searchAllBrand(device,search147);
        verifyProduct(device,searchResultAccessoriesPage,search147);
        searchAllBrand(device,search148);
        verifyProduct(device,searchResultAccessoriesPage,search148);
        searchAllBrand(device,search149);
        verifyProduct(device,searchResultAccessoriesPage,search149);
        searchAllBrand(device,search150);
        verifyProduct(device,searchResultAccessoriesPage,search150);
        searchAllBrand(device,search151);
        verifyProduct(device,searchResultAccessoriesPage,search151);
        searchAllBrand(device,search152);
        verifyProduct(device,searchResultAccessoriesPage,search152);
        searchAllBrand(device,search153);
        verifyProduct(device,searchResultAccessoriesPage,search153);
        searchAllBrand(device,search154);
        verifyProduct(device,searchResultAccessoriesPage,search154);
        searchAllBrand(device,search155);
        verifyProduct(device,searchResultAccessoriesPage,search155);
        searchAllBrand(device,search156);
        verifyProduct(device,searchResultAccessoriesPage,search156);
        searchAllBrand(device,search157);
        verifyProduct(device,searchResultAccessoriesPage,search157);
        searchAllBrand(device,search158);
        verifyProduct(device,searchResultAccessoriesPage,search158);
        searchAllBrand(device,search159);
        verifyProduct(device,searchResultAccessoriesPage,search159);
        searchAllBrand(device,search160);
        verifyProduct(device,searchResultAccessoriesPage,search160);
        searchAllBrand(device,search161);
        verifyProduct(device,searchResultAccessoriesPage,search161);
        searchAllBrand(device,search162);
        verifyProduct(device,searchResultAccessoriesPage,search162);
        searchAllBrand(device,search163);
        verifyProduct(device,searchResultAccessoriesPage,search163);
        searchAllBrand(device,search164);
        verifyProduct(device,searchResultAccessoriesPage,search164);
        searchAllBrand(device,search165);
        verifyProduct(device,searchResultAccessoriesPage,search165);
        searchAllBrand(device,search166);
        verifyProduct(device,searchResultAccessoriesPage,search166);
        searchAllBrand(device,search167);
        verifyProduct(device,searchResultAccessoriesPage,search167);
        searchAllBrand(device,search168);
        verifyProduct(device,searchResultAccessoriesPage,search168);
        searchAllBrand(device,search169);
        verifyProduct(device,searchResultAccessoriesPage,search169);
        searchAllBrand(device,search170);
        verifyProduct(device,searchResultAccessoriesPage,search170);
        searchAllBrand(device,search171);
        verifyProduct(device,searchResultAccessoriesPage,search171);
        searchAllBrand(device,search172);
        verifyProduct(device,searchResultAccessoriesPage,search172);
        searchAllBrand(device,search173);
        verifyProduct(device,searchResultAccessoriesPage,search173);
        searchAllBrand(device,search174);
        verifyProduct(device,searchResultAccessoriesPage,search174);
        searchAllBrand(device,search175);
        verifyProduct(device,searchResultAccessoriesPage,search175);
        searchAllBrand(device,search176);
        verifyProduct(device,searchResultAccessoriesPage,search176);
        searchAllBrand(device,search177);
        verifyProduct(device,searchResultAccessoriesPage,search177);
        searchAllBrand(device,search178);
        verifyProduct(device,searchResultAccessoriesPage,search178);
        searchAllBrand(device,search179);
        verifyProduct(device,searchResultAccessoriesPage,search179);
        searchAllBrand(device,search180);
        verifyProduct(device,searchResultAccessoriesPage,search180);
        searchAllBrand(device,search181);
        verifyProduct(device,searchResultAccessoriesPage,search181);
        searchAllBrand(device,search182);
        verifyProduct(device,searchResultAccessoriesPage,search182);
        searchAllBrand(device,search183);
        verifyProduct(device,searchResultAccessoriesPage,search183);
        searchAllBrand(device,search184);
        verifyProduct(device,searchResultAccessoriesPage,search184);
        searchAllBrand(device,search185);
        verifyProduct(device,searchResultAccessoriesPage,search185);
        searchAllBrand(device,search186);
        verifyProduct(device,searchResultAccessoriesPage,search186);
        searchAllBrand(device,search187);
        verifyProduct(device,searchResultAccessoriesPage,search187);
        searchAllBrand(device,search188);
        verifyProduct(device,searchResultAccessoriesPage,search188);
        searchAllBrand(device,search189);
        verifyProduct(device,searchResultAccessoriesPage,search189);
        searchAllBrand(device,search190);
        verifyProduct(device,searchResultAccessoriesPage,search190);
        searchAllBrand(device,search191);
        verifyProduct(device,searchResultAccessoriesPage,search191);
        searchAllBrand(device,search192);
        verifyProduct(device,searchResultAccessoriesPage,search192);
        searchAllBrand(device,search193);
        verifyProduct(device,searchResultAccessoriesPage,search193);
        searchAllBrand(device,search194);
        verifyProduct(device,searchResultAccessoriesPage,search194);
        searchAllBrand(device,search195);
        verifyProduct(device,searchResultAccessoriesPage,search195);
        searchAllBrand(device,search196);
        verifyProduct(device,searchResultAccessoriesPage,search196);
        searchAllBrand(device,search197);
        verifyProduct(device,searchResultAccessoriesPage,search197);
        searchAllBrand(device,search198);
        verifyProduct(device,searchResultAccessoriesPage,search198);
        searchAllBrand(device,search199);
        verifyProduct(device,searchResultAccessoriesPage,search199);
        searchAllBrand(device,search200);
        verifyProduct(device,searchResultAccessoriesPage,search200);

        searchAllBrand(device,search201);
        verifyProduct(device,searchResultAccessoriesPage,search201);
        searchAllBrand(device,search202);
        verifyProduct(device,searchResultAccessoriesPage,search202);
        searchAllBrand(device,search203);
        verifyProduct(device,searchResultAccessoriesPage,search203);
        searchAllBrand(device,search204);
        verifyProduct(device,searchResultAccessoriesPage,search204);
        searchAllBrand(device,search205);
        verifyProduct(device,searchResultAccessoriesPage,search205);
        searchAllBrand(device,search206);
        verifyProduct(device,searchResultAccessoriesPage,search206);
        searchAllBrand(device,search207);
        verifyProduct(device,searchResultAccessoriesPage,search207);
        searchAllBrand(device,search208);
        verifyProduct(device,searchResultAccessoriesPage,search208);
        searchAllBrand(device,search209);
        verifyProduct(device,searchResultAccessoriesPage,search209);
        searchAllBrand(device,search210);
        verifyProduct(device,searchResultAccessoriesPage,search210);

        searchAllBrand(device,search211);
        verifyProduct(device,searchResultAccessoriesPage,search211);
        searchAllBrand(device,search212);
        verifyProduct(device,searchResultAccessoriesPage,search212);
        searchAllBrand(device,search213);
        verifyProduct(device,searchResultAccessoriesPage,search213);
        searchAllBrand(device,search214);
        verifyProduct(device,searchResultAccessoriesPage,search214);
        searchAllBrand(device,search215);
        verifyProduct(device,searchResultAccessoriesPage,search215);
        searchAllBrand(device,search216);
        verifyProduct(device,searchResultAccessoriesPage,search216);
        searchAllBrand(device,search217);
        verifyProduct(device,searchResultAccessoriesPage,search217);
        searchAllBrand(device,search218);
        verifyProduct(device,searchResultAccessoriesPage,search218);
        searchAllBrand(device,search219);
        verifyProduct(device,searchResultAccessoriesPage,search219);
        searchAllBrand(device,search220);
        verifyProduct(device,searchResultAccessoriesPage,search220);
        searchAllBrand(device,search221);
        verifyProduct(device,searchResultAccessoriesPage,search221);
        searchAllBrand(device,search222);
        verifyProduct(device,searchResultAccessoriesPage,search222);
        searchAllBrand(device,search223);
        verifyProduct(device,searchResultAccessoriesPage,search223);
        searchAllBrand(device,search224);
        verifyProduct(device,searchResultAccessoriesPage,search224);
        searchAllBrand(device,search225);
        verifyProduct(device,searchResultAccessoriesPage,search225);
        searchAllBrand(device,search226);
        verifyProduct(device,searchResultAccessoriesPage,search226);
        searchAllBrand(device,search227);
        verifyProduct(device,searchResultAccessoriesPage,search227);
        searchAllBrand(device,search228);
        verifyProduct(device,searchResultAccessoriesPage,search228);
        searchAllBrand(device,search229);
        verifyProduct(device,searchResultAccessoriesPage,search229);
        searchAllBrand(device,search230);
        verifyProduct(device,searchResultAccessoriesPage,search230);
        searchAllBrand(device,search231);
        verifyProduct(device,searchResultAccessoriesPage,search231);
        searchAllBrand(device,search232);
        verifyProduct(device,searchResultAccessoriesPage,search232);
        searchAllBrand(device,search233);
        verifyProduct(device,searchResultAccessoriesPage,search233);
        searchAllBrand(device,search234);
        verifyProduct(device,searchResultAccessoriesPage,search234);
        searchAllBrand(device,search235);
        verifyProduct(device,searchResultAccessoriesPage,search235);
        searchAllBrand(device,search236);
        verifyProduct(device,searchResultAccessoriesPage,search236);
        searchAllBrand(device,search237);
        verifyProduct(device,searchResultAccessoriesPage,search237);
        searchAllBrand(device,search238);
        verifyProduct(device,searchResultAccessoriesPage,search238);
        searchAllBrand(device,search239);
        verifyProduct(device,searchResultAccessoriesPage,search239);
        searchAllBrand(device,search240);
        verifyProduct(device,searchResultAccessoriesPage,search240);
        searchAllBrand(device,search241);
        verifyProduct(device,searchResultAccessoriesPage,search241);
        searchAllBrand(device,search242);
        verifyProduct(device,searchResultAccessoriesPage,search242);
        searchAllBrand(device,search243);
        verifyProduct(device,searchResultAccessoriesPage,search243);
        searchAllBrand(device,search244);
        verifyProduct(device,searchResultAccessoriesPage,search244);
        searchAllBrand(device,search245);
        verifyProduct(device,searchResultAccessoriesPage,search245);
        searchAllBrand(device,search246);
        verifyProduct(device,searchResultAccessoriesPage,search246);
        searchAllBrand(device,search247);
        verifyProduct(device,searchResultAccessoriesPage,search247);
        searchAllBrand(device,search248);
        verifyProduct(device,searchResultAccessoriesPage,search248);
        searchAllBrand(device,search249);
        verifyProduct(device,searchResultAccessoriesPage,search249);
        searchAllBrand(device,search250);
        verifyProduct(device,searchResultAccessoriesPage,search250);
        searchAllBrand(device,search251);
        verifyProduct(device,searchResultAccessoriesPage,search251);
        searchAllBrand(device,search252);
        verifyProduct(device,searchResultAccessoriesPage,search252);
        searchAllBrand(device,search253);
        verifyProduct(device,searchResultAccessoriesPage,search253);
        searchAllBrand(device,search254);
        verifyProduct(device,searchResultAccessoriesPage,search254);
        searchAllBrand(device,search255);
        verifyProduct(device,searchResultAccessoriesPage,search255);
        searchAllBrand(device,search256);
        verifyProduct(device,searchResultAccessoriesPage,search256);
        searchAllBrand(device,search257);
        verifyProduct(device,searchResultAccessoriesPage,search257);
        searchAllBrand(device,search258);
        verifyProduct(device,searchResultAccessoriesPage,search258);
        searchAllBrand(device,search259);
        verifyProduct(device,searchResultAccessoriesPage,search259);
        searchAllBrand(device,search260);
        verifyProduct(device,searchResultAccessoriesPage,search260);
        searchAllBrand(device,search261);
        verifyProduct(device,searchResultAccessoriesPage,search261);
        searchAllBrand(device,search262);
        verifyProduct(device,searchResultAccessoriesPage,search262);
        searchAllBrand(device,search263);
        verifyProduct(device,searchResultAccessoriesPage,search263);
        searchAllBrand(device,search264);
        verifyProduct(device,searchResultAccessoriesPage,search264);
        searchAllBrand(device,search265);
        verifyProduct(device,searchResultAccessoriesPage,search265);
        searchAllBrand(device,search266);
        verifyProduct(device,searchResultAccessoriesPage,search266);
        searchAllBrand(device,search267);
        verifyProduct(device,searchResultAccessoriesPage,search267);
        searchAllBrand(device,search268);
        verifyProduct(device,searchResultAccessoriesPage,search268);
        searchAllBrand(device,search269);
        verifyProduct(device,searchResultAccessoriesPage,search269);
        searchAllBrand(device,search270);
        verifyProduct(device,searchResultAccessoriesPage,search270);
        searchAllBrand(device,search271);
        verifyProduct(device,searchResultAccessoriesPage,search271);
        searchAllBrand(device,search272);
        verifyProduct(device,searchResultAccessoriesPage,search272);
        searchAllBrand(device,search273);
        verifyProduct(device,searchResultAccessoriesPage,search273);
        searchAllBrand(device,search274);
        verifyProduct(device,searchResultAccessoriesPage,search274);
        searchAllBrand(device,search275);
        verifyProduct(device,searchResultAccessoriesPage,search275);
        searchAllBrand(device,search276);
        verifyProduct(device,searchResultAccessoriesPage,search276);
        searchAllBrand(device,search277);
        verifyProduct(device,searchResultAccessoriesPage,search277);
        searchAllBrand(device,search278);
        verifyProduct(device,searchResultAccessoriesPage,search278);
        searchAllBrand(device,search279);
        verifyProduct(device,searchResultAccessoriesPage,search279);
        searchAllBrand(device,search280);
        verifyProduct(device,searchResultAccessoriesPage,search280);
        searchAllBrand(device,search281);
        verifyProduct(device,searchResultAccessoriesPage,search281);
        searchAllBrand(device,search282);
        verifyProduct(device,searchResultAccessoriesPage,search282);
        searchAllBrand(device,search283);
        verifyProduct(device,searchResultAccessoriesPage,search283);
        searchAllBrand(device,search284);
        verifyProduct(device,searchResultAccessoriesPage,search284);
        searchAllBrand(device,search285);
        verifyProduct(device,searchResultAccessoriesPage,search285);
        searchAllBrand(device,search286);
        verifyProduct(device,searchResultAccessoriesPage,search286);
        searchAllBrand(device,search287);
        verifyProduct(device,searchResultAccessoriesPage,search287);
        searchAllBrand(device,search288);
        verifyProduct(device,searchResultAccessoriesPage,search288);
        searchAllBrand(device,search289);
        verifyProduct(device,searchResultAccessoriesPage,search289);
        searchAllBrand(device,search290);
        verifyProduct(device,searchResultAccessoriesPage,search290);
        searchAllBrand(device,search291);
        verifyProduct(device,searchResultAccessoriesPage,search291);
        searchAllBrand(device,search292);
        verifyProduct(device,searchResultAccessoriesPage,search292);
        searchAllBrand(device,search293);
        verifyProduct(device,searchResultAccessoriesPage,search293);
        searchAllBrand(device,search294);
        verifyProduct(device,searchResultAccessoriesPage,search294);
        searchAllBrand(device,search295);
        verifyProduct(device,searchResultAccessoriesPage,search295);
        searchAllBrand(device,search296);
        verifyProduct(device,searchResultAccessoriesPage,search296);
        searchAllBrand(device,search297);
        verifyProduct(device,searchResultAccessoriesPage,search297);
        searchAllBrand(device,search298);
        verifyProduct(device,searchResultAccessoriesPage,search298);
        searchAllBrand(device,search299);
        verifyProduct(device,searchResultAccessoriesPage,search299);
        //driver.quit();
    }
}
