package Regression.TitleTagProducts;

import Automation.TestBase;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

/**
 * Created with IntelliJ IDEA.
 * User: KHALLBEC
 * Date: 3/17/13
 * Time: 6:22 PM
 * To change this template use File | Settings | File Templates.
 */
public class TitleTags48150 extends TestBase {

    //change the Strings below to change the tests
    String testNumber = "48150";
    String typeOfTest = "Regression";
    String typeOfCust = "NA";
    String typeOfPayment = "Credit";
    String searchAllBrand = "solution";
    //LENSES//
    String AcuvueLenses = "lenses/acuvue";
    String Acuvue2Lenses = "lenses/acuvue-2";
    String AcuvueAdvanceLenses = "lenses/acuvue-advance";
    String AvairaLenses="lenses/avaira";
    String AirOptixLenses = "lenses/air-optix";
    String AcuvueOasysLenses = "lenses/acuvue-oasys";
    String AcuvueMoistLenses = "lenses/1-day-acuvue-moist";
    String AcuvuetrueyeLenses = "lenses/acuvue-trueye";
    String AqualensLenses = "lenses/aqualens";
    String AqualiteLenses = "lenses/aqualite";
    String BauschLenses = "Lenses/bausch-lomb";
    String BifocalLenses = "lenses/bifocal";
    String BiofinityLenses = "lenses/biofinity";
    String BiomedicsLenses = "lenses/biomedics";
    String CibaLenses = "lenses/ciba-vision";
    String ClearLabLenses = "lenses/clearlab";
    String ClearsightLenses = "lenses/clearsight";
    String ColorLenses = "lenses/color";
    String CooperVisionLenses = "lenses/coopervision";
    String DailiesLenses = "Lenses/dailies";
    String DailyDisosablesLenses = "Lenses/Daily-Disposables";
    String EncoreLenses = "lenses/encore";
    String ExtremeH2OLenses = "lenses/extreme-h2o";
    String FlextiqueLenses = "lenses/flextique";
    String FocusLenses = "lenses/focus";
    String FocusDailiesLenses = "lenses/focus-dailies";
    String FrequencyLenses = "lenses/frequency";
    String FreshlookLenses = "lenses/freshlook";
    String H2OLenses = "lenses/h2o";
    String HydrogelLenses = "lenses/hydrogel";
    String MediflexLenses = "lenses/mediflex";
    String MonthlyDisposablesLenses = "lenses/monthly-disposables";
    String OptimaLenses = "lenses/optima";
    String OptixLenses = "lenses/optix";
    String PolysoftLenses = "lenses/polysoft";
    String PreferenceLenses = "lenses/preference";
    String ProclearLenses = "lenses/proclear";
    String ProflexLenses = "lenses/proflex";
    String PrositeLenses = "lenses/prosite";
    String ProvisionLenses = "lenses/provision";
    String PurevisionLenses = "lenses/purevision";
    String SoflensLenses = "lenses/soflens";
    String SofmedLenses = "lenses/sofmed";
    String SterlingLenses = "lenses/sterling";
    String TargetLenses = "lenses/target";
    String ToricLenses = "lenses/toric";
    String UltraflexLenses = "lenses/ultraflex-7-14";
    String VersaflexLenses = "lenses/versaflex";
    String VertexLenses = "lenses/vertex";
    String VialLenses = "lenses/vial";
    String WeeklyDisposablesLenses = "lenses/weekly-disposables";
    //LENS//
    String DayAcuvue30pk="lens/1-day-acuvue-30";
    String DayAcuvueMoist90pk="lens/1-day-acuvue-moist-90";
    String DayAcuvueTruEye30pk="lens/1-day-acuvue-trueye-30";
    String DayAcuvueMoist30pk="lens/1-day-acuvue-moist-30";
    String DayAcuvueMoistforAstigmatism30pk="lens/1-day-acuvue-moist-for-astigmatism-30";
    String DayAcuvueTruEye90pk="lens/1-day-acuvue-trueye-90";
    String Acuvue="lens/acuvue";
    String Acuvue2Colours="lens/acuvue-2-colours";
    String AcuvueAdvanceAstigmatism="lens/acuvue-advance-for-astigmatism" ;
    String AcuvueAdvancePlus6pk="lens/acuvue-advance-plus-6";
    String AcuvueOasysAstigmatism="lens/acuvue-oasys-for-astigmatism" ;
    String AcuvueOasysHydraclearPlus24pk="lens/acuvue-oasys-24" ;
    String AirOptixAqua="lens/air-optix-aqua";
    String Aqualens38="lens/aqualens-38";
    String Aqualens55Aspheric="lens/aqualens-55-aspheric";
    String Aqualite55="lens/aqualite-55";
    String Avaira="lens/avaira";
    String Acuvue2="lens/acuvue-2" ;
    String AcuvueAdvance="lens/acuvue-advance" ;
    String AcuvueAdvancePlus24pk="lens/acuvue-advance-plus-24";
    String AcuvueBifocals="lens/acuvue-bifocals";
    String AcuvueOasysPresbyopia="lens/acuvue-oasys-for-presbyopia";
    String AcuvueOasysHydraclearPlus6pk="lens/acuvue-oasys";
    String AirOptixAquaMultifocal="lens/air-optix-aqua-multifocal";
    String AirOptixNightDayAqua="lens/air-optix-night-day-aqua";
    String Aqualens55="lens/aqualens-55";
    String Aqualite38="lens/aqualite-38";
    String Aqualite55ProAspheric="lens/aqualite-55-pro-aspheric" ;
    String AvairaToric="lens/avaira-toric";
    String Biofinity="lens/biofinity";
    String BiofinityToric="lens/biofinity-toric";
    String Biomedics38="lens/biomedics-38" ;
    String Biomedics55Evolution="lens/biomedics-55-evolution" ;
    String BiomedicsEP="lens/biomedics-ep";
    String BiomedicsXC="lens/biomedics-xc";
    String BiofinityMultifocal="lens/biofinity-multifocal";
    String Biomedics1Day90pk="lens/biomedics-1-day-90" ;
    String Biomedics55="lens/biomedics-55" ;
    String Biomedics55Premier="lens/biomedics-55-premier";
    String BiomedicsToric="lens/biomedics-toric" ;
    String ClarityH2O="lens/clarity-h2o";
    String Clear58="lens/clear-58" ;
    String ClearSightDay30pk="lens/clearsight-1-day-30";
    String ClearSight1DayToric30pk="lens/clearsight-1-day-toric-30";
    String Clear55A="lens/clear-55a";
    String ClearAllDay="lens/clear-all-day";
    String ClearSight1Day90pk="lens/clearsight-1-day-90" ;
    String DailiesAquaComfortPlus30pk="lens/dailies-aquacomfort-plus-30";
    String DailiesAquaComfortPlus90pk="lens/dailies-aquacomfort-plus-90" ;
    String EncorePremium="lens/encore-premium" ;
    String ExtremeH2O54136="lens/extreme-h2o-54-13-6" ;
    String ExtremeH2O54ToricLC="lens/extreme-h2o-54-toric-lc" ;
    String ExtremeH2O59Thin="lens/extreme-h2o-59-thin" ;
    String Expressions="lens/expressions" ;
    String ExtremeH2O54142="lens/extreme-h2o-54-14-2" ;
    String ExtremeH2O54ToricMC="lens/extreme-h2o-54-toric-mc";
    String ExtremeH2O59Xtra="lens/extreme-h2o-59-xtra";
    String Flextique38="lens/flextique-38" ;
    String Flextique55Aspheric="lens/flextique-55-aspheric" ;
    String FocusDAILIES90pk="lens/focus-dailies-90";
    String FocusDAILIESToric30pk="lens/focus-dailies-toric-30" ;
    String FocusMonthlySoftcolors="lens/focus-monthly-softcolors";
    String Frequency55Aspheric="lens/frequency-55-aspheric";
    String Frequency55Toric="lens/frequency-55-toric" ;
    String FreshLookColorblends="lens/freshlook-colorblends" ;
    String FreshLookColors="lens/freshlook-colors";
    String FreshLookHandlingTint="lens/freshlook-handling-tint";
    String FreshLookToric="lens/freshlook-toric";
    String Flextique55="lens/flextique-55";
    String FocusDAILIES30pk="lens/focus-dailies-30";
    String FocusDAILIESProgressives30pk="lens/focus-dailies-progressives-30";
    String FocusDAILIESToric90pk="lens/focus-dailies-toric-90" ;
    String Frequency55="lens/frequency-55" ;
    String Frequency55Multifocal="lens/frequency-55-multifocal" ;
    String Frequency55ToricXR="lens/frequency-55-toric-xr" ;
    String FreshLookColorblendsToric="lens/freshlook-colorblends-toric";
    String FreshLookDimensions="lens/freshlook-dimensions" ;
    String FreshLookONEDAY="lens/freshlook-one-day";
    String IcuityH2O="lens/icuity-h2o" ;
    String Mediflex38="lens/mediflex-38" ;
    String Mediflex55="lens/mediflex-55" ;
    String O2Optix="lens/o2-optix" ;
    String OptimaFW="lens/optima-fw" ;
    String Optima38SP="lens/optima-38-sp";
    String OptimaToric="lens/optima-toric" ;
    String Perspecta55Aspheric="lens/perspecta-55-aspheric" ;
    String Polysoft55="lens/polysoft-55";
    String PreferenceDWFW="lens/preference-dw-fw";
    String PreferenceToric="lens/preference-toric";
    String Proclear1Day90pk="lens/proclear-1-day-90" ;
    String ProclearEP="lens/proclear-ep" ;
    String ProclearToric="lens/proclear-toric" ;
    String Proflex38="lens/proflex-38" ;
    String Prosite38="lens/prosite-38";
    String Prosite55Aspheric="lens/prosite-55-aspheric" ;
    String ProvisionPremium="lens/provision-premium" ;
    String PureVision2="lens/purevision-2-hd";
    String PureVisionMultiFocal="lens/purevision-multi-focal";
    String Polysoft38="lens/polysoft-38";
    String Polysoft55Aspheric="lens/polysoft-55-aspheric";
    String PreferenceStandard="lens/preference-standard";
    String Proclear="lens/proclear";
    String Proclear1DayMultifocal30pk="lens/proclear-1-day-multifocal-30" ;
    String ProclearMultifocal="lens/proclear-multifocal";
    String ProclearToricXR="lens/proclear-toric-xr";
    String Proflex55="lens/proflex-55" ;
    String Prosite55="lens/prosite-55";
    String Provision55="lens/provision-55";
    String PureVision="lens/purevision";
    String PureVision2HDforAstigmatism="lens/purevision-2-hd-for-astigmatism";
    String PureVisionToric="lens/purevision-toric";
    String SofLens38="lens/soflens-38" ;
    String SofLensDailyDisposables90pk="lens/soflens-daily-disposables-90" ;
    String SofLensToric="lens/soflens-toric" ;
    String Sofmed55Aspheric="lens/sofmed-55-aspheric";
    String SoftconEW="lens/softcon-ew";
    String Sterling55="lens/sterling-55";
    String SofLensDailyDisposableforAstigmatism="lens/soflens-daily-disposable-for-astigmatism-30";
    String SofLensMultiFocal="lens/soflens-multi-focal";
    String Sofmed38="lens/sofmed-38";
    String Sofmed55="lens/sofmed-55";
    String Sterling38="lens/sterling-38";
    String Sterling55Aspheric="lens/sterling-55-aspheric";
    String Target38="lens/target-38";
    String Target55Aspheric="lens/target-55-aspheric";
    String Target55="lens/target-55";
    String UltraFlex71438="lens/ultraflex-7-14-38";
    String UltraFlexIIAspheric="lens/ultraflex-II-aspheric";
    String UltraFlexXC="lens/ultraflex-xc";
    String UltraFlex71455="lens/ultraflex-7-14-55";
    String UltraFlexToric="lens/ultraflex-toric";
    String Versaflex38="lens/versaflex-38";
    String Versaflex55Aspheric="lens/versaflex-55-aspheric";
    String VertexToric="lens/vertex-toric";
    String Versaflex55="lens/versaflex-55";
    String VertexSphere="lens/vertex-sphere";
    String VertexToricXR="lens/vertex-toric-xr";
        String rebateNotShipped = "Your order has not shipped yet.";
    String orderStatus = "Checking Stock";
    String shippingVerify = "Title tag";
    String printTestName = typeOfTest + " | " + testNumber + " | " + typeOfCust + " | " + searchAllBrand + " | " + typeOfPayment + " | " + shippingVerify;
    String screenshotTestName =  testNumber + "_" + typeOfTest + "_" + typeOfCust + "_" + searchAllBrand + "_" + typeOfPayment + "_" + shippingVerify;



    @Test (singleThreaded = true)
    @Parameters(value = "device")
    public void titleTagTest(String device) {
        openWebPage(device);
        takeScreenshot(screenshotTestName, "Interstitial");
        clickNoThanksButton(device);
        printTestNumber(printTestName);
        gotoPageVTitle(DayAcuvue30pk,"1-Day Acuvue 30 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(DayAcuvueMoist90pk,"1-Day Acuvue Moist 90 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(DayAcuvueTruEye30pk,"1-Day Acuvue TruEye 30 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(DayAcuvueMoist30pk,"1-Day Acuvue Moist 30 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(DayAcuvueMoistforAstigmatism30pk,"1-Day Acuvue Moist for Astigmatism 30 Pack | 1-800 CONTACTS");
        gotoPageVTitle(DayAcuvueTruEye90pk,"1-Day Acuvue TruEye 90 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Acuvue,"Acuvue Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Acuvue2Colours,"Acuvue 2 Colours Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueAdvanceAstigmatism,"Acuvue Advance for Astigmatism Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueAdvancePlus6pk,"Acuvue Advance Plus 6 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueOasysAstigmatism,"Acuvue Oasys for Astigmatism Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueOasysHydraclearPlus24pk,"Acuvue Oasys with Hydraclear Plus 24 Pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(AirOptixAqua,"Air Optix Aqua Contact Lenses| 1-800 CONTACTS");
        gotoPageVTitle(Aqualens38,"Aqualens 38 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Aqualens55Aspheric,"Aqualens 55 Aspheric Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Aqualite55,"Aqualite 55 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Avaira,"Avaira Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Acuvue2,"Acuvue 2 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueAdvance,"Acuvue Advance with Hydraclear Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueAdvancePlus24pk,"Acuvue Advance Plus 24 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueBifocals,"Acuvue Bifocals Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueOasysPresbyopia,"Acuvue Oasys for Presbyopia Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AcuvueOasysHydraclearPlus6pk,"Acuvue Oasys with Hydraclear Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AirOptixAquaMultifocal,"Air Optix Aqua Multifocal Contact Lenses| 1-800 CONTACTS");
        gotoPageVTitle(AirOptixNightDayAqua,"Air Optix Night & Day Aqua Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Aqualens55,"Aqualens 55 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Aqualite38,"Aqualite 38 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Aqualite55ProAspheric,"Aqualite 55 Pro Aspheric Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(AvairaToric ,"Avaira Toric Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Biofinity,"Biofinity Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(BiofinityToric,"Biofinity Toric Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Biomedics38,"Biomedics 38 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Biomedics55Evolution,"Biomedics 55 Evolution Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(BiomedicsEP,"Biomedics EP (Proclear EP) Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(BiomedicsXC,"Biomedics XC Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(BiofinityMultifocal,"Biofinity Multifocal Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Biomedics1Day90pk,"Biomedics 1-Day 90 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Biomedics55,"Biomedics 55 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Biomedics55Premier,"Biomedics 55 Premier Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(BiomedicsToric,"Biomedics Toric Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ClarityH2O,"Clarity H2O Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Clear58,"Clear 58 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ClearSightDay30pk,"ClearSight 1 Day 30 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ClearSight1DayToric30pk,"ClearSight 1 Day Toric 30 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Clear55A,"Clear 55A Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ClearAllDay,"Clear All-Day Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ClearSight1Day90pk,"ClearSight 1 Day 90 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(DailiesAquaComfortPlus30pk,"Dailies AquaComfort Plus 30 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(DailiesAquaComfortPlus90pk,"Dailies AquaComfort Plus 90 Pack Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(EncorePremium,"Encore Premium Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ExtremeH2O54136,"Extreme H2O 54% 13.6 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ExtremeH2O54ToricLC,"Extreme H2O 54% Toric LC Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ExtremeH2O59Thin,"Extreme H2O 59% Thin Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Expressions,"Expressions Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ExtremeH2O54142,"Extreme H2O 54% 14.2 Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ExtremeH2O54ToricMC,"Extreme H2O 54% Toric MC Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(ExtremeH2O59Xtra,"Extreme H2O 59% Xtra Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Flextique38,"Flextique 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Flextique55Aspheric,"Flextique 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FocusDAILIES90pk,"Focus DAILIES 90 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FocusDAILIESToric30pk,"Focus DAILIES Toric 30 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FocusMonthlySoftcolors,"Focus Monthly Softcolors at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Frequency55Aspheric,"Frequency 55 Aspheric Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle(Frequency55Toric,"Frequency 55 Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookColorblends,"FreshLook Colorblends at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookColors,"FreshLook Colors at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookHandlingTint,"FreshLook Handling Tint at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookToric,"FreshLook Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Flextique55,"Flextique 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FocusDAILIES30pk,"Focus DAILIES 30 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FocusDAILIESProgressives30pk,"Focus DAILIES Progressives 30 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FocusDAILIESToric90pk,"Focus DAILIES Toric 90 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Frequency55,"Frequency 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Frequency55Multifocal,"Frequency 55 Multifocal at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Frequency55ToricXR,"Frequency 55 Toric XR at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookColorblendsToric,"FreshLook Colorblends Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookDimensions,"FreshLook Dimensions at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(FreshLookONEDAY,"FreshLook ONE-DAY at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(IcuityH2O,"Icuity H2O at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Mediflex38,"Mediflex 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Mediflex55,"Mediflex 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(O2Optix,"O2 Optix at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(OptimaFW,"Optima FW (Soflens 38) at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Optima38SP,"Optima 38/SP at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(OptimaToric,"Optima Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Perspecta55Aspheric,"Perspecta 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Polysoft55,"Polysoft 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PreferenceDWFW,"Preference DW/FW at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PreferenceToric,"Preference Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Proclear1Day90pk,"Proclear 1-Day 90 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(ProclearEP,"Proclear EP (Biomedics EP) at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(ProclearToric,"Proclear Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Proflex38,"Proflex 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Prosite38,"Prosite 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Prosite55Aspheric,"Prosite 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(ProvisionPremium,"Provision Premium at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PureVision2,"PureVision 2 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PureVisionMultiFocal,"PureVision Multi-Focal at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Polysoft38,"Polysoft 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Polysoft55Aspheric,"Polysoft 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PreferenceStandard,"Preference Standard at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Proclear,"Proclear at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Proclear1DayMultifocal30pk,"Proclear 1-Day Multifocal 30 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(ProclearMultifocal,"Proclear Multifocal at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(ProclearToricXR,"Proclear Toric XR at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Proflex55,"Proflex 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Prosite55,"Prosite 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Provision55,"Provision 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PureVision ,"PureVision at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PureVision2HDforAstigmatism,"PureVision 2 HD for Astigmatism at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(PureVisionToric,"PureVision Toric (PureVision For Astigmatism) at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(SofLens38,"SofLens 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(SofLensDailyDisposables90pk,"SofLens Daily Disposables 90 pack at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(SofLensToric,"SofLens Toric (SofLens For Astigmatism) at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Sofmed55Aspheric,"Sofmed 55 Aspheric/UltraFlex II Asp at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(SoftconEW,"Softcon EW at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Sterling55,"Sterling 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(SofLensDailyDisposableforAstigmatism,"SofLens Daily Disposable for Astigmatism at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(SofLensMultiFocal,"SofLens Multi-Focal at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Sofmed38,"Sofmed 38/UltraFlex 7/14 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Sofmed55,"Sofmed 55/UltraFlex 7/14 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Sterling38,"Sterling 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Sterling55Aspheric,"Sterling 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Target38,"Target 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Target55Aspheric,"Target 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Target55,"Target 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(UltraFlex71438,"UltraFlex 7/14 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(UltraFlexIIAspheric,"UltraFlex II Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(UltraFlexXC,"UltraFlex XC at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(UltraFlex71455,"UltraFlex 7/14 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(UltraFlexToric,"UltraFlex Toric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Versaflex38,"Versaflex 38 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Versaflex55Aspheric,"Versaflex 55 Aspheric at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(VertexToric,"Vertex Toric (Encore Toric) at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(Versaflex55,"Versaflex 55 at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(VertexSphere,"Vertex Sphere (Encore Sphere) at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle(VertexToricXR,"Vertex Toric XR at 1-800 CONTACTS | World's Largest Contact Lens Store");
        gotoPageVTitle (AcuvueLenses,"Acuvue Brand Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (Acuvue2Lenses,"Acuvue2Lenses");
        gotoPageVTitle (AcuvueAdvanceLenses,"AcuvueAdvanceLenses");
        gotoPageVTitle (AvairaLenses,"Avaira Brand Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (AirOptixLenses,"Air Optix Brand Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (AcuvueOasysLenses,"AcuvueOasysLenses");
        gotoPageVTitle (AcuvueMoistLenses,"AcuvueMoistLenses");
        gotoPageVTitle (AcuvuetrueyeLenses,"AcuvuetrueyeLenses");
        gotoPageVTitle (AqualensLenses,"AqualensLenses");
        gotoPageVTitle (AqualiteLenses,"AqualiteLenses");
        gotoPageVTitle (BauschLenses,"Bausch & Lomb Brand Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (BifocalLenses,"Bifocal Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (BiofinityLenses,"Biofinity Brand Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (BiomedicsLenses,"Biomedics Brand Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (CibaLenses,"CIBA Vision Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (ClearLabLenses,"ClearLabLenses");
        gotoPageVTitle (ClearsightLenses,"ClearsightLenses");
        gotoPageVTitle (ColorLenses,"Colored Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (CooperVisionLenses,"CooperVision Contact Lenses | 1-800 CONTACTS");
        gotoPageVTitle (DailiesLenses,"DailiesLenses");
        gotoPageVTitle (DailyDisosablesLenses,"DailyDisosablesLenses");
        gotoPageVTitle (EncoreLenses,"EncoreLenses");
        gotoPageVTitle (ExtremeH2OLenses,"ExtremeH2OLenses");
        gotoPageVTitle (FlextiqueLenses,"FlextiqueLenses");
        gotoPageVTitle (FocusLenses,"FocusLenses");
        gotoPageVTitle (FocusDailiesLenses ,"FocusDailiesLenses");
        gotoPageVTitle (FrequencyLenses ,"FrequencyLenses");
        gotoPageVTitle (FreshlookLenses,"FreshlookLenses");
        gotoPageVTitle (H2OLenses,"H2OLenses");
        gotoPageVTitle (HydrogelLenses,"HydrogelLenses");
        gotoPageVTitle (MediflexLenses,"MediflexLenses");
        gotoPageVTitle (MonthlyDisposablesLenses,"MonthlyDisposablesLenses");
        gotoPageVTitle (OptimaLenses,"OptimaLenses");
        gotoPageVTitle (OptixLenses,"OptixLenses");
        gotoPageVTitle (PolysoftLenses,"PolysoftLenses");
        gotoPageVTitle (PreferenceLenses,"PreferenceLenses");
        gotoPageVTitle (ProclearLenses,"ProclearLenses");
        gotoPageVTitle (ProflexLenses,"ProflexLenses");
        gotoPageVTitle (PrositeLenses,"PrositeLenses");
        gotoPageVTitle (ProvisionLenses,"ProvisionLenses");
        gotoPageVTitle (PurevisionLenses,"PurevisionLenses");
        gotoPageVTitle (SoflensLenses,"SoflensLenses");
        gotoPageVTitle (SofmedLenses,"SofmedLenses");
        gotoPageVTitle (SterlingLenses,"SterlingLenses");
        gotoPageVTitle (TargetLenses,"TargetLenses");
        gotoPageVTitle (ToricLenses,"ToricLenses");
        gotoPageVTitle (UltraflexLenses,"UltraflexLenses");
        gotoPageVTitle (VersaflexLenses,"VersaflexLenses");
        gotoPageVTitle (VertexLenses,"VertexLenses");
        gotoPageVTitle (VialLenses,"VialLenses");
        gotoPageVTitle (WeeklyDisposablesLenses,"1-2 Week Disposable Contact Lenses | 1-800 CONTACTS");
        driver.quit();
    }
}
